server:
  port: 8878
  context-path: /user
eureka:
  client: 
    healthcheck:
      enabled:true
    service-url:
      defaultZone: http://user:password123@www.renxl.club:10020/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}   
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）

# 个人对eureka租期续约的理解，客户端定期注册，服务端定期扫描，客户端还有一个注册失败的清除时间


  
  
  
#redis
# Redis数据库索引（默认为0）
#spring.redis.database=0
# Redis服务器地址
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
# spring.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
# 连接池最大阻塞等待时间（使用负值表示没有限制）
# 连接池中的最大空闲连接
# 连接池中的最小空闲连接
# 连接超时时间（毫秒）

# --------------------------- mysql start -------------------------
# 用户角色为分库分表，其他全部都是字典表，先采用单库单表分案
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://47.104.88.31:3306/axin20180823?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: abcde12345
    driverClassName: com.mysql.jdbc.Driver
# --------------------------- mysql end ---------------------------
#
#
# --------------------------- mybatis start -------------------------
#
mybatis:
  mapperLocations: classpath*:club.renxl.www.user.ssocenter.dao/*.xml
  typeAliasesPackage: club.renxl.www.user.ssocenter.dao.domain
  #pagehelper分00页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# --------------------------- mybatis end ---------------------------

# 文件上传设置    
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 100Mb
