package club.renxl.www.user.ssocenter.dao.domain;

public class Area {
    /** ID */
    private String id;

    /** 栏目名 */
    private String areaname;

    /** 父栏目 */
    private String parentid;

    /**  */
    private String shortname;

    /** 经度 */
    private Double lng;

    /** 纬度 */
    private Double lat;

    /**  */
    private Boolean level;

    /** 25 */
    private String position;

    /** 排序 */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.id
     *
     * @return the value of usercenter_area.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.id
     *
     * @param id the value for usercenter_area.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.areaname
     *
     * @return the value of usercenter_area.areaname
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.areaname
     *
     * @param areaname the value for usercenter_area.areaname
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.parentid
     *
     * @return the value of usercenter_area.parentid
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.parentid
     *
     * @param parentid the value for usercenter_area.parentid
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.shortname
     *
     * @return the value of usercenter_area.shortname
     *
     * @mbggenerated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.shortname
     *
     * @param shortname the value for usercenter_area.shortname
     *
     * @mbggenerated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.lng
     *
     * @return the value of usercenter_area.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.lng
     *
     * @param lng the value for usercenter_area.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.lat
     *
     * @return the value of usercenter_area.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.lat
     *
     * @param lat the value for usercenter_area.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.level
     *
     * @return the value of usercenter_area.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.level
     *
     * @param level the value for usercenter_area.level
     *
     * @mbggenerated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.position
     *
     * @return the value of usercenter_area.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.position
     *
     * @param position the value for usercenter_area.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_area.sort
     *
     * @return the value of usercenter_area.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_area.sort
     *
     * @param sort the value for usercenter_area.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}