package club.renxl.www.user.ssocenter.dao.domain;

import java.util.Date;

public class Permission {
    /**  */
    private Integer id;

    /** 名称 */
    private String name;

    /** 编码 */
    private String code;

    /** 类型0菜单1按钮 */
    private Byte type;

    /** 路径 */
    private String path;

    /** 页面路径 */
    private String page;

    /** 父级id,顶级为0 */
    private Integer pid;

    /** 状态 1启用 0禁用 */
    private String status;

    /** 顺序 */
    private Byte seq;

    /** 描述 */
    private String description;

    /** 创建时间 */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.id
     *
     * @return the value of usercenter_permission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.id
     *
     * @param id the value for usercenter_permission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.name
     *
     * @return the value of usercenter_permission.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.name
     *
     * @param name the value for usercenter_permission.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.code
     *
     * @return the value of usercenter_permission.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.code
     *
     * @param code the value for usercenter_permission.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.type
     *
     * @return the value of usercenter_permission.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.type
     *
     * @param type the value for usercenter_permission.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.path
     *
     * @return the value of usercenter_permission.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.path
     *
     * @param path the value for usercenter_permission.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.page
     *
     * @return the value of usercenter_permission.page
     *
     * @mbggenerated
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.page
     *
     * @param page the value for usercenter_permission.page
     *
     * @mbggenerated
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.pid
     *
     * @return the value of usercenter_permission.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.pid
     *
     * @param pid the value for usercenter_permission.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.status
     *
     * @return the value of usercenter_permission.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.status
     *
     * @param status the value for usercenter_permission.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.seq
     *
     * @return the value of usercenter_permission.seq
     *
     * @mbggenerated
     */
    public Byte getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.seq
     *
     * @param seq the value for usercenter_permission.seq
     *
     * @mbggenerated
     */
    public void setSeq(Byte seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.description
     *
     * @return the value of usercenter_permission.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.description
     *
     * @param description the value for usercenter_permission.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_permission.create_time
     *
     * @return the value of usercenter_permission.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_permission.create_time
     *
     * @param createTime the value for usercenter_permission.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}