package club.renxl.www.user.ssocenter.dao.domain;

import java.util.Date;

public class Role {
    /**  */
    private Integer id;

    /**  */
    private String roleName;

    /**  */
    private Long createUserId;

    /**  */
    private String createUserName;

    /**  */
    private Integer modifyUserId;

    /**  */
    private String modifyUserName;

    /**  */
    private Date createDate;

    /**  */
    private Date modifyDate;

    /**  */
    private String status;

    /**  */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.id
     *
     * @return the value of usercenter_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.id
     *
     * @param id the value for usercenter_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.role_name
     *
     * @return the value of usercenter_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.role_name
     *
     * @param roleName the value for usercenter_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.create_user_id
     *
     * @return the value of usercenter_role.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.create_user_id
     *
     * @param createUserId the value for usercenter_role.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.create_user_name
     *
     * @return the value of usercenter_role.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.create_user_name
     *
     * @param createUserName the value for usercenter_role.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.modify_user_id
     *
     * @return the value of usercenter_role.modify_user_id
     *
     * @mbggenerated
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.modify_user_id
     *
     * @param modifyUserId the value for usercenter_role.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.modify_user_name
     *
     * @return the value of usercenter_role.modify_user_name
     *
     * @mbggenerated
     */
    public String getModifyUserName() {
        return modifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.modify_user_name
     *
     * @param modifyUserName the value for usercenter_role.modify_user_name
     *
     * @mbggenerated
     */
    public void setModifyUserName(String modifyUserName) {
        this.modifyUserName = modifyUserName == null ? null : modifyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.create_date
     *
     * @return the value of usercenter_role.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.create_date
     *
     * @param createDate the value for usercenter_role.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.modify_date
     *
     * @return the value of usercenter_role.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.modify_date
     *
     * @param modifyDate the value for usercenter_role.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.status
     *
     * @return the value of usercenter_role.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.status
     *
     * @param status the value for usercenter_role.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role.is_deleted
     *
     * @return the value of usercenter_role.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role.is_deleted
     *
     * @param isDeleted the value for usercenter_role.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}