package club.renxl.www.user.ssocenter.dao.domain;

public class RolePermission {
    /**  */
    private Integer id;

    /** 用户编码 */
    private Integer roleId;

    /** 权限id */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role_permission.id
     *
     * @return the value of usercenter_role_permission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role_permission.id
     *
     * @param id the value for usercenter_role_permission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role_permission.role_id
     *
     * @return the value of usercenter_role_permission.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role_permission.role_id
     *
     * @param roleId the value for usercenter_role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_role_permission.permission_id
     *
     * @return the value of usercenter_role_permission.permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_role_permission.permission_id
     *
     * @param permissionId the value for usercenter_role_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}