package club.renxl.www.user.ssocenter.dao.domain;

import java.util.Date;

public class Schcool {
    /**  */
    private Integer id;

    /** 机构唯一码 */
    private String code;

    /** 查询码 */
    private String seqCode;

    /** 名称 */
    private String name;

    /** 简称 */
    private String shortName;

    /** 传真 */
    private String fax;

    /** 具体地址 */
    private String address;

    /** 责任人 */
    private String resName;

    /** 责任人电话 */
    private String resPhone;

    /** 资格证书编号 */
    private String qualification;

    /** 描述 */
    private String description;

    /** 创建时间 */
    private Date createDate;

    /** 更新时间 */
    private Date updateDate;

    /** 类型：1,维保单位，2,物业单位(使用单位)，3,质检单位，4,救援单位，5,街道，6,社区，7厂商 ，8产权单位 9设计单位 10 制造单位 11电梯安装单位 */
    private Byte type;

    /** 机构状态 1使用中 0已禁用 */
    private String status;

    /** 机构状态 1已激活 0未激活 */
    private String activStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.id
     *
     * @return the value of usercenter_schcool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.id
     *
     * @param id the value for usercenter_schcool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.code
     *
     * @return the value of usercenter_schcool.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.code
     *
     * @param code the value for usercenter_schcool.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.seq_code
     *
     * @return the value of usercenter_schcool.seq_code
     *
     * @mbggenerated
     */
    public String getSeqCode() {
        return seqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.seq_code
     *
     * @param seqCode the value for usercenter_schcool.seq_code
     *
     * @mbggenerated
     */
    public void setSeqCode(String seqCode) {
        this.seqCode = seqCode == null ? null : seqCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.name
     *
     * @return the value of usercenter_schcool.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.name
     *
     * @param name the value for usercenter_schcool.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.short_name
     *
     * @return the value of usercenter_schcool.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.short_name
     *
     * @param shortName the value for usercenter_schcool.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.fax
     *
     * @return the value of usercenter_schcool.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.fax
     *
     * @param fax the value for usercenter_schcool.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.address
     *
     * @return the value of usercenter_schcool.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.address
     *
     * @param address the value for usercenter_schcool.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.res_name
     *
     * @return the value of usercenter_schcool.res_name
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.res_name
     *
     * @param resName the value for usercenter_schcool.res_name
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.res_phone
     *
     * @return the value of usercenter_schcool.res_phone
     *
     * @mbggenerated
     */
    public String getResPhone() {
        return resPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.res_phone
     *
     * @param resPhone the value for usercenter_schcool.res_phone
     *
     * @mbggenerated
     */
    public void setResPhone(String resPhone) {
        this.resPhone = resPhone == null ? null : resPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.qualification
     *
     * @return the value of usercenter_schcool.qualification
     *
     * @mbggenerated
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.qualification
     *
     * @param qualification the value for usercenter_schcool.qualification
     *
     * @mbggenerated
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.description
     *
     * @return the value of usercenter_schcool.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.description
     *
     * @param description the value for usercenter_schcool.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.create_date
     *
     * @return the value of usercenter_schcool.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.create_date
     *
     * @param createDate the value for usercenter_schcool.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.update_date
     *
     * @return the value of usercenter_schcool.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.update_date
     *
     * @param updateDate the value for usercenter_schcool.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.type
     *
     * @return the value of usercenter_schcool.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.type
     *
     * @param type the value for usercenter_schcool.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.status
     *
     * @return the value of usercenter_schcool.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.status
     *
     * @param status the value for usercenter_schcool.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_schcool.activ_status
     *
     * @return the value of usercenter_schcool.activ_status
     *
     * @mbggenerated
     */
    public String getActivStatus() {
        return activStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_schcool.activ_status
     *
     * @param activStatus the value for usercenter_schcool.activ_status
     *
     * @mbggenerated
     */
    public void setActivStatus(String activStatus) {
        this.activStatus = activStatus == null ? null : activStatus.trim();
    }
}