package club.renxl.www.user.ssocenter.dao.domain;

public class UserRole {
    /**  */
    private Integer id;

    /**  */
    private Long userId;

    /**  */
    private Integer roleId;

    /**  */
    private Long createUserId;

    /**  */
    private String createUserName;

    /**  */
    private String modifyUserId;

    /**  */
    private String modifyUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.id
     *
     * @return the value of usercenter_user_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.id
     *
     * @param id the value for usercenter_user_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.user_id
     *
     * @return the value of usercenter_user_role.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.user_id
     *
     * @param userId the value for usercenter_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.role_id
     *
     * @return the value of usercenter_user_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.role_id
     *
     * @param roleId the value for usercenter_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.create_user_id
     *
     * @return the value of usercenter_user_role.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.create_user_id
     *
     * @param createUserId the value for usercenter_user_role.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.create_user_name
     *
     * @return the value of usercenter_user_role.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.create_user_name
     *
     * @param createUserName the value for usercenter_user_role.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.modify_user_id
     *
     * @return the value of usercenter_user_role.modify_user_id
     *
     * @mbggenerated
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.modify_user_id
     *
     * @param modifyUserId the value for usercenter_user_role.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId == null ? null : modifyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user_role.modify_user_name
     *
     * @return the value of usercenter_user_role.modify_user_name
     *
     * @mbggenerated
     */
    public String getModifyUserName() {
        return modifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user_role.modify_user_name
     *
     * @param modifyUserName the value for usercenter_user_role.modify_user_name
     *
     * @mbggenerated
     */
    public void setModifyUserName(String modifyUserName) {
        this.modifyUserName = modifyUserName == null ? null : modifyUserName.trim();
    }
}