package club.renxl.www.user.ssocenter.dao.domain;

import java.util.Date;

public class User {
    /** 编号 */
    private Long id;

    /** 登录名 */
    private String username;

    /** 密码 */
    private String password;

    /** 状态 1可用 0禁用 */
    private Boolean status;

    /** 最后登录时间 */
    private Date lastLoginTime;

    /** 登录IP */
    private String lastLoginIp;

    /** 姓名 */
    private String realName;

    /** 身份证号 */
    private String idCard;

    /** 邮箱 */
    private String email;

    /** 手机号码 */
    private String userPhone;

    /** 省份 */
    private String province;

    /** 城市 */
    private String city;

    /** 区县 */
    private String area;

    /** 详细地址 */
    private String address;

    /** 头像 */
    private String nickImg;

    /** 昵称 */
    private String nickName;

    /** 角色集合，逗号分隔；所有用户只有角色概念；部门具有角色但本身不是角色 */
    private String role;

    /** 支付宝 */
    private String alipay;

    /**  */
    private String qq;

    /**  */
    private String wx;

    /**  */
    private String others;

    /**  */
    private String alipayJsonData;

    /**  */
    private String wxJsonData;

    /**  */
    private String appType;

    /**  */
    private String appUser;

    /** 第三方凭证 */
    private String appToken;

    /** 1老师2学生3学校管理人员4其他 */
    private String schoolUserType;

    /** 学生一卡通账号，老师，老师一卡通账号或编号等等 */
    private Integer schoolCardId;

    /** 年级1，2，3，4，（研究生）5，6，7（博士）a,b,c */
    private String schoolClass;

    /** 当前主专业 */
    private String schoolSubject;

    /** 双修专业，或历史专业，换专业等等的学生,逗号分隔 */
    private String schoolOtherSubject;

    /** 是否已经毕业1大学中，2留级生，3毕业 */
    private String schoolGraduate;

    /** 大学待几年，默认4年 */
    private Integer schoolYear;

    /** 学校名称;后期需要添加code */
    private String schoolName;

    /** 学院名称,后期需要添加code */
    private String schoolAcademy;

    /** 省份代码 */
    private String provinceCode;

    /** 区县代码 */
    private String areaCode;

    /** 城市代码 */
    private String cityCode;

    /** 注册时间 */
    private Date registerTime;

    /** 修改时间 */
    private Date modifyTime;

    /** 删除标记:0已删除 1未删除 */
    private String isDeleted;

    /** 身份证正面 */
    private String idCardImgFace;

    /** 身份证反面 */
    private String idCardImgInfo;

    /** 学校id */
    private Integer schoolId;

    /** 学院id */
    private Integer schoolAcademyId;

    /** 主专业id */
    private Integer schoolSubjectId;

    /** 行政区域code */
    private String provincesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.id
     *
     * @return the value of usercenter_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.id
     *
     * @param id the value for usercenter_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.username
     *
     * @return the value of usercenter_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.username
     *
     * @param username the value for usercenter_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.password
     *
     * @return the value of usercenter_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.password
     *
     * @param password the value for usercenter_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.status
     *
     * @return the value of usercenter_user.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.status
     *
     * @param status the value for usercenter_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.last_login_time
     *
     * @return the value of usercenter_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.last_login_time
     *
     * @param lastLoginTime the value for usercenter_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.last_login_ip
     *
     * @return the value of usercenter_user.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.last_login_ip
     *
     * @param lastLoginIp the value for usercenter_user.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.real_name
     *
     * @return the value of usercenter_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.real_name
     *
     * @param realName the value for usercenter_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.id_card
     *
     * @return the value of usercenter_user.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.id_card
     *
     * @param idCard the value for usercenter_user.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.email
     *
     * @return the value of usercenter_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.email
     *
     * @param email the value for usercenter_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.user_phone
     *
     * @return the value of usercenter_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.user_phone
     *
     * @param userPhone the value for usercenter_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.province
     *
     * @return the value of usercenter_user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.province
     *
     * @param province the value for usercenter_user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.city
     *
     * @return the value of usercenter_user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.city
     *
     * @param city the value for usercenter_user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.area
     *
     * @return the value of usercenter_user.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.area
     *
     * @param area the value for usercenter_user.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.address
     *
     * @return the value of usercenter_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.address
     *
     * @param address the value for usercenter_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.nick_img
     *
     * @return the value of usercenter_user.nick_img
     *
     * @mbggenerated
     */
    public String getNickImg() {
        return nickImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.nick_img
     *
     * @param nickImg the value for usercenter_user.nick_img
     *
     * @mbggenerated
     */
    public void setNickImg(String nickImg) {
        this.nickImg = nickImg == null ? null : nickImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.nick_name
     *
     * @return the value of usercenter_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.nick_name
     *
     * @param nickName the value for usercenter_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.role
     *
     * @return the value of usercenter_user.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.role
     *
     * @param role the value for usercenter_user.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.alipay
     *
     * @return the value of usercenter_user.alipay
     *
     * @mbggenerated
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.alipay
     *
     * @param alipay the value for usercenter_user.alipay
     *
     * @mbggenerated
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay == null ? null : alipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.qq
     *
     * @return the value of usercenter_user.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.qq
     *
     * @param qq the value for usercenter_user.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.wx
     *
     * @return the value of usercenter_user.wx
     *
     * @mbggenerated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.wx
     *
     * @param wx the value for usercenter_user.wx
     *
     * @mbggenerated
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.others
     *
     * @return the value of usercenter_user.others
     *
     * @mbggenerated
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.others
     *
     * @param others the value for usercenter_user.others
     *
     * @mbggenerated
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.alipay_json_data
     *
     * @return the value of usercenter_user.alipay_json_data
     *
     * @mbggenerated
     */
    public String getAlipayJsonData() {
        return alipayJsonData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.alipay_json_data
     *
     * @param alipayJsonData the value for usercenter_user.alipay_json_data
     *
     * @mbggenerated
     */
    public void setAlipayJsonData(String alipayJsonData) {
        this.alipayJsonData = alipayJsonData == null ? null : alipayJsonData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.wx_json_data
     *
     * @return the value of usercenter_user.wx_json_data
     *
     * @mbggenerated
     */
    public String getWxJsonData() {
        return wxJsonData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.wx_json_data
     *
     * @param wxJsonData the value for usercenter_user.wx_json_data
     *
     * @mbggenerated
     */
    public void setWxJsonData(String wxJsonData) {
        this.wxJsonData = wxJsonData == null ? null : wxJsonData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.app_type
     *
     * @return the value of usercenter_user.app_type
     *
     * @mbggenerated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.app_type
     *
     * @param appType the value for usercenter_user.app_type
     *
     * @mbggenerated
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.app_user
     *
     * @return the value of usercenter_user.app_user
     *
     * @mbggenerated
     */
    public String getAppUser() {
        return appUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.app_user
     *
     * @param appUser the value for usercenter_user.app_user
     *
     * @mbggenerated
     */
    public void setAppUser(String appUser) {
        this.appUser = appUser == null ? null : appUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.app_token
     *
     * @return the value of usercenter_user.app_token
     *
     * @mbggenerated
     */
    public String getAppToken() {
        return appToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.app_token
     *
     * @param appToken the value for usercenter_user.app_token
     *
     * @mbggenerated
     */
    public void setAppToken(String appToken) {
        this.appToken = appToken == null ? null : appToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_user_type
     *
     * @return the value of usercenter_user.school_user_type
     *
     * @mbggenerated
     */
    public String getSchoolUserType() {
        return schoolUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_user_type
     *
     * @param schoolUserType the value for usercenter_user.school_user_type
     *
     * @mbggenerated
     */
    public void setSchoolUserType(String schoolUserType) {
        this.schoolUserType = schoolUserType == null ? null : schoolUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_card_id
     *
     * @return the value of usercenter_user.school_card_id
     *
     * @mbggenerated
     */
    public Integer getSchoolCardId() {
        return schoolCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_card_id
     *
     * @param schoolCardId the value for usercenter_user.school_card_id
     *
     * @mbggenerated
     */
    public void setSchoolCardId(Integer schoolCardId) {
        this.schoolCardId = schoolCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_class
     *
     * @return the value of usercenter_user.school_class
     *
     * @mbggenerated
     */
    public String getSchoolClass() {
        return schoolClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_class
     *
     * @param schoolClass the value for usercenter_user.school_class
     *
     * @mbggenerated
     */
    public void setSchoolClass(String schoolClass) {
        this.schoolClass = schoolClass == null ? null : schoolClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_subject
     *
     * @return the value of usercenter_user.school_subject
     *
     * @mbggenerated
     */
    public String getSchoolSubject() {
        return schoolSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_subject
     *
     * @param schoolSubject the value for usercenter_user.school_subject
     *
     * @mbggenerated
     */
    public void setSchoolSubject(String schoolSubject) {
        this.schoolSubject = schoolSubject == null ? null : schoolSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_other_subject
     *
     * @return the value of usercenter_user.school_other_subject
     *
     * @mbggenerated
     */
    public String getSchoolOtherSubject() {
        return schoolOtherSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_other_subject
     *
     * @param schoolOtherSubject the value for usercenter_user.school_other_subject
     *
     * @mbggenerated
     */
    public void setSchoolOtherSubject(String schoolOtherSubject) {
        this.schoolOtherSubject = schoolOtherSubject == null ? null : schoolOtherSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_graduate
     *
     * @return the value of usercenter_user.school_graduate
     *
     * @mbggenerated
     */
    public String getSchoolGraduate() {
        return schoolGraduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_graduate
     *
     * @param schoolGraduate the value for usercenter_user.school_graduate
     *
     * @mbggenerated
     */
    public void setSchoolGraduate(String schoolGraduate) {
        this.schoolGraduate = schoolGraduate == null ? null : schoolGraduate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_year
     *
     * @return the value of usercenter_user.school_year
     *
     * @mbggenerated
     */
    public Integer getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_year
     *
     * @param schoolYear the value for usercenter_user.school_year
     *
     * @mbggenerated
     */
    public void setSchoolYear(Integer schoolYear) {
        this.schoolYear = schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_name
     *
     * @return the value of usercenter_user.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_name
     *
     * @param schoolName the value for usercenter_user.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_academy
     *
     * @return the value of usercenter_user.school_academy
     *
     * @mbggenerated
     */
    public String getSchoolAcademy() {
        return schoolAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_academy
     *
     * @param schoolAcademy the value for usercenter_user.school_academy
     *
     * @mbggenerated
     */
    public void setSchoolAcademy(String schoolAcademy) {
        this.schoolAcademy = schoolAcademy == null ? null : schoolAcademy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.province_code
     *
     * @return the value of usercenter_user.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.province_code
     *
     * @param provinceCode the value for usercenter_user.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.area_code
     *
     * @return the value of usercenter_user.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.area_code
     *
     * @param areaCode the value for usercenter_user.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.city_code
     *
     * @return the value of usercenter_user.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.city_code
     *
     * @param cityCode the value for usercenter_user.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.register_time
     *
     * @return the value of usercenter_user.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.register_time
     *
     * @param registerTime the value for usercenter_user.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.modify_time
     *
     * @return the value of usercenter_user.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.modify_time
     *
     * @param modifyTime the value for usercenter_user.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.is_deleted
     *
     * @return the value of usercenter_user.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.is_deleted
     *
     * @param isDeleted the value for usercenter_user.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.id_card_img_face
     *
     * @return the value of usercenter_user.id_card_img_face
     *
     * @mbggenerated
     */
    public String getIdCardImgFace() {
        return idCardImgFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.id_card_img_face
     *
     * @param idCardImgFace the value for usercenter_user.id_card_img_face
     *
     * @mbggenerated
     */
    public void setIdCardImgFace(String idCardImgFace) {
        this.idCardImgFace = idCardImgFace == null ? null : idCardImgFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.id_card_img_info
     *
     * @return the value of usercenter_user.id_card_img_info
     *
     * @mbggenerated
     */
    public String getIdCardImgInfo() {
        return idCardImgInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.id_card_img_info
     *
     * @param idCardImgInfo the value for usercenter_user.id_card_img_info
     *
     * @mbggenerated
     */
    public void setIdCardImgInfo(String idCardImgInfo) {
        this.idCardImgInfo = idCardImgInfo == null ? null : idCardImgInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_id
     *
     * @return the value of usercenter_user.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_id
     *
     * @param schoolId the value for usercenter_user.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_academy_id
     *
     * @return the value of usercenter_user.school_academy_id
     *
     * @mbggenerated
     */
    public Integer getSchoolAcademyId() {
        return schoolAcademyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_academy_id
     *
     * @param schoolAcademyId the value for usercenter_user.school_academy_id
     *
     * @mbggenerated
     */
    public void setSchoolAcademyId(Integer schoolAcademyId) {
        this.schoolAcademyId = schoolAcademyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.school_subject_id
     *
     * @return the value of usercenter_user.school_subject_id
     *
     * @mbggenerated
     */
    public Integer getSchoolSubjectId() {
        return schoolSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.school_subject_id
     *
     * @param schoolSubjectId the value for usercenter_user.school_subject_id
     *
     * @mbggenerated
     */
    public void setSchoolSubjectId(Integer schoolSubjectId) {
        this.schoolSubjectId = schoolSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercenter_user.provinces_id
     *
     * @return the value of usercenter_user.provinces_id
     *
     * @mbggenerated
     */
    public String getProvincesId() {
        return provincesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercenter_user.provinces_id
     *
     * @param provincesId the value for usercenter_user.provinces_id
     *
     * @mbggenerated
     */
    public void setProvincesId(String provincesId) {
        this.provincesId = provincesId == null ? null : provincesId.trim();
    }
}