package club.renxl.www.user.ssocenter.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import club.renxl.www.user.ssocenter.dao.domain.Schcool;
import club.renxl.www.user.ssocenter.dao.domain.SchcoolExample;

public interface SchcoolMapper   {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int countByExample(SchcoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int deleteByExample(SchcoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int insert(Schcool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int insertSelective(Schcool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    List<Schcool> selectByExample(SchcoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    Schcool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Schcool record, @Param("example") SchcoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Schcool record, @Param("example") SchcoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schcool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercenter_schcool
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schcool record);
}